// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBly_xBcfdj1B19el6mx_6yz3ItnTpBCj4',
    appId: '1:701737845048:web:eee976f5a10b689bda41cd',
    messagingSenderId: '701737845048',
    projectId: 'agri-house',
    authDomain: 'agri-house.firebaseapp.com',
    storageBucket: 'agri-house.appspot.com',
    measurementId: 'G-8K3J4XQ5DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuoJYlwBt68WMrlqBVFAKGq_TPqvK__zI',
    appId: '1:701737845048:android:a8b787fff33f8be2da41cd',
    messagingSenderId: '701737845048',
    projectId: 'agri-house',
    storageBucket: 'agri-house.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5H_-96OqfREsHcy8gcrDzHLQVMSZeKg',
    appId: '1:701737845048:ios:dc434a79fc38ce29da41cd',
    messagingSenderId: '701737845048',
    projectId: 'agri-house',
    storageBucket: 'agri-house.appspot.com',
    iosBundleId: 'com.example.testimn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5H_-96OqfREsHcy8gcrDzHLQVMSZeKg',
    appId: '1:701737845048:ios:dc434a79fc38ce29da41cd',
    messagingSenderId: '701737845048',
    projectId: 'agri-house',
    storageBucket: 'agri-house.appspot.com',
    iosBundleId: 'com.example.testimn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBly_xBcfdj1B19el6mx_6yz3ItnTpBCj4',
    appId: '1:701737845048:web:84fb768023e461d2da41cd',
    messagingSenderId: '701737845048',
    projectId: 'agri-house',
    authDomain: 'agri-house.firebaseapp.com',
    storageBucket: 'agri-house.appspot.com',
    measurementId: 'G-EMTJGC2RWZ',
  );
}
